.gitignore
package-lock.json
package.json
public/index.html
src/App.js
src/components/core/CoreDashboard.js
src/components/core/MessageCard.js

Added core dashboard

---

src/components/core/CoreDashboard.js

Made core dashboard responsive

---

src/components/core/CoreDashboard.js
src/components/core/MessageCard.js

Modifications in core dashboard

---

src/App.js
src/components/letterpopup/LetterPopup.css
src/components/letterpopup/ReadMessagePopup.js
src/components/letterpopup/SendMessagePopup.js

Lacked closing mechanism in MessagePopups.
Fixes #
Fixes related to the components stated below.
Added the said mechanism. A new prop must be used with both the MessagePopups -- enabled. Values can be true or false. This is compulsory.
N/A

Added closing/opening mechanisms to Send/Read MessagePopups

---

src/components/login/login.js

Changed redirect uri

---

src/components/core/CoreDashboard.js

UI fixes to core dashboard

---

src/components/admin/AdminDashboard.js
src/components/admin/MessageCard.js
src/components/letterpopup/ReadMessagePopup.js
src/components/personal/personal.js
src/components/personal/personalcards.js

Fixes #
Admin Dashboard bugs.
-
-
-

Admin Dashboard bug fixes

---

src/components/core/CoreDashboard.js
src/components/core/MessageCard.js
src/components/login/login.js

Fetch messages from API done for Core

---

src/components/admin/AdminDashboard.js
src/components/admin/MessageCard.js
src/components/popups/AssignCoreMembersPopup.js
src/components/util/url.js

Fixes #
- All APIs covered for admin dashboard
-
-

Admin Dashboard Integrations completed

---

src/components/core/CoreDashboard.js
src/components/login/login.js

Safeguarding routes

---

src/components/navbar/navbar.css
src/components/navbar/navbar.js
src/components/navbar/profile.js
src/components/navbar/search.css
src/components/navbar/search.js
src/components/personal/personal.css
src/components/personal/personal.js
src/components/personal/personalcards.js

navbar complete and with search filter left

---

.github/workflows/main.yml

Slow CI time
Fixes #
Speed up CI

update to have shorter linting times

---

src/components/letterpopup/SendMessagePopup.js

bug solved

---

src/components/letterpopup/LetterPopup.css
src/components/personal/personalcards.js

media query fixes in read

---

src/components/admin/AdminDashboard.js
src/components/popups/AssignCoreMembersPopup.js

Fixes #
Fixes First 25, First 50 and First x in Admin dashboard
-
-
-

Admin dashboard first 25, forst 50 logic improved

---

src/components/letterpopup/LetterPopup.css
src/components/letterpopup/ReadMessagePopup.js
src/components/letterpopup/SendMessagePopup.js
src/components/navbar/navbar.css
src/components/navbar/profile.js
src/components/personal/personal.js

pagination fix and letter fix

---

src/components/admin/AdminDashboard.js
src/components/core/CoreDashboard.js
src/components/personal/personal.js

Router guards update bug fix

---

src/components/letterpopup/LetterPopup.css
src/components/letterpopup/SendMessagePopup1.js
src/components/navbar/navbar.js
src/components/navbar/profile.js
src/components/personal/personal.css
src/components/personal/personal.js

new search done and fixes

---

src/components/core/CoreDashboard.js

Removed padding for screen size in core dashboard paginator

---

src/components/admin/AdminDashboard.js
src/components/popups/AssignCoreMembersPopup.js

Fixes #
- Admin Dashboard fixed
-
-

Admin Dashboard fixes

---

src/components/admin/AdminDashboard.js
src/components/admin/MessageCard.js
src/components/core/CoreDashboard.js
src/components/core/MessageCard.js

Fixes #
- Consistent UI across Admin and Core Dashboard.
-
-

UI made consistent across Admin and Core and other fixes

---

src/components/core/CoreDashboard.js

Changed index of cards on core

---

src/components/admin/AdminDashboard.js

changes revoked

---

src/components/admin/AdminDashboard.js
src/components/admin/MessageCard.js
src/components/admin/Statistics.js
src/components/core/CoreDashboard.js
src/components/core/MessageCard.js
src/components/navbar/navbar.js
src/components/navbar/profile.js
src/index.js

Admin Dashboard UI fixes

---

src/components/personal/loader.css

loader css change

---

src/components/core/CoreDashboard.js
src/components/core/MessageCard.js

Added reload button to core dashboard and fixed snackbar bug.

---

src/components/admin/AdminDashboard.js
src/components/admin/MessageCard.js

Another bug

---

src/components/credits/credits.css
src/components/letterpopup/SendMessagePopup.js
src/components/navbar/navbar.css
src/components/navbar/navbar.js
src/components/navbar/profile.js

redirect to home

---

src/components/admin/AdminDashboard.js
src/components/admin/MessageCard.js
src/components/admin/Statistics.js
src/components/core/CoreDashboard.js
src/components/credits/credits.js
src/components/personal/personal.js
src/components/popups/AssignCoreMembersPopup.js

Admin Dashboard not selected messages alert display, scrollbars made same

---

src/components/personal/personal.js

final case

---

src/components/welcome/welcome.css
src/components/welcome/welcome.js

home page writeup

---

src/components/letterpopup/ReadMessagePopup.js
src/components/letterpopup/SendMessagePopup.js
src/components/personal/personal.js
src/components/personal/personalcards.js
src/components/welcome/welcome.css
src/components/welcome/welcome.js

website crash fail safe and loaders

---

src/components/letterpopup/LetterPopup.css
src/components/letterpopup/ReadMessagePopup.js
src/components/letterpopup/SendMessagePopup.js
src/components/letterpopup/sendmessage.css

Fixes #
-Have made UI changes
-position of the loader has been made appropriate
-

position of loader changed

---

src/components/admin/MessageCard.js
src/components/admin/Statistics.js

Only basic stats shown. Also admin dashboard message card's UI was not consistent earlier.
Fixes #
- Stats now shows info of all core members
- Admin Dashboard message card extra padding removed for consistent UI
-

Updated Stats and Minor UI change in Admin Dashboard

---

src/components/credits/creds1.js

Organising commitee -> Coordinators

---

src/components/admin/Statistics.js
src/components/letterpopup/SendMessagePopup.js
src/components/letterpopup/sendmessage.css
src/components/navbar/notifs.js

Fixes #
UI issue in send message popup

Send message popup UI fix and stats page error removed

---

src/components/letterpopup/sendmessage.css

Overflow fix

---

src/components/admin/AdminDashboard.js
src/components/popups/AssignCoreMembersPopup.js

- [1 ] Bugfix
Fixes #
-fixed admin panel assign by search issue
-
-

fixed admin panel assign by search issue

---

src/components/admin/AdminDashboard.js

some more edge cases of admin panel

---

src/components/admin/AdminDashboard.js

Fixes #
-the last test and edge case my eyes and brain could find here..Hopefully its the best case fit now 
-
-

last set of edge cases pls Hopefully
